export const vocabulary = [
  { character: "都", pinyin: "dōu", english: "both/all", enabled: true },
  { character: "很", pinyin: "hěn", english: "very", enabled: true },
  { character: "学院", pinyin: "xuéyuàn", english: "college/institute", enabled: true },
  { character: "可以", pinyin: "kěyǐ", english: "can/may", enabled: true },
  { character: "这", pinyin: "zhè", english: "this", enabled: true },
  { character: "餐厅", pinyin: "cāntīng", english: "dining hall, etc", enabled: true },
  { character: "进", pinyin: "jìn", english: "enter (v)", enabled: true },
  { character: "层", pinyin: "céng", english: "story/level", enabled: true },
  { character: "宿舍", pinyin: "sùshè", english: "dormitory", enabled: true },
  { character: "来", pinyin: "lái", english: "to come/arrive", enabled: true },
  { character: "对不起", pinyin: "duìbuqǐ", english: "sorry", enabled: true },
  { character: "下课", pinyin: "xià kè", english: "finish class", enabled: true },
  { character: "外婆", pinyin: "wàipó", english: "maternal grandmother", enabled: true },
  { character: "没关系", pinyin: "méi guānxi", english: "nevermind/doesn't matter", enabled: true },
  { character: "为什么", pinyin: "wèi shénme", english: "why (for what)", enabled: true },
  { character: "现在", pinyin: "xiànzài", english: "right now", enabled: true },
  { character: "时候", pinyin: "shíhou", english: "time (less abstract)", enabled: true },
  { character: "时间", pinyin: "shíjiān", english: "time (more abstract)", enabled: true },
  { character: "陈", pinyin: "Chén", english: "Chen (surname)", enabled: true },
  { character: "名字", pinyin: "míngzi", english: "name", enabled: true },
  { character: "教授", pinyin: "jiàoshòu", english: "professor", enabled: true },
  { character: "张", pinyin: "zhāng", english: "surname (and MW flats)", enabled: true },
  { character: "公里", pinyin: "gōnglǐ", english: "kilometer", enabled: true },
  { character: "怎么样", pinyin: "zěnmeyàng", english: "how (was something)", enabled: true },
  { character: "京剧", pinyin: "jīngjù", english: "Beijing Opera", enabled: true },
  { character: "恐怕", pinyin: "kǒngpà", english: "afraid that...", enabled: true },
  { character: "抱歉", pinyin: "bàoqiàn", english: "sorry", enabled: true },
  { character: "看", pinyin: "kàn", english: "to watch or look at", enabled: true },
  { character: "开学", pinyin: "kāixué", english: "beginning of school (VO)", enabled: true },
  { character: "名片", pinyin: "míngpiàn", english: "business card", enabled: true },
  { character: "介绍", pinyin: "jièshào", english: "introduce (v)", enabled: true },
  { character: "先生", pinyin: "xiānsheng", english: "sir", enabled: true },
  { character: "专业", pinyin: "zhuānyè", english: "major/specialization", enabled: true },
  { character: "中文", pinyin: "zhōngwén", english: "Chinese language", enabled: true },
  { character: "美术", pinyin: "měishù", english: "fine arts", enabled: true },
  { character: "系", pinyin: "xì", english: "department", enabled: true },
  { character: "文学", pinyin: "wénxué", english: "literature", enabled: true },
  { character: "家", pinyin: "jiā", english: "home/family", enabled: true },
  { character: "照片", pinyin: "zhàopiàn", english: "photo", enabled: true },
  { character: "还", pinyin: "hái", english: "in addition", enabled: true },
  { character: "工作", pinyin: "gōngzuò", english: "work/job", enabled: true },
  { character: "喜欢", pinyin: "xǐhuān", english: "like", enabled: true },
  { character: "吃", pinyin: "chī", english: "eat", enabled: true },
  { character: "几", pinyin: "jǐ", english: "how many", enabled: true },
  { character: "一共", pinyin: "yígòng", english: "altogether", enabled: true },
  { character: "当然", pinyin: "dāngrán", english: "of course", enabled: true },
  { character: "和", pinyin: "hé", english: "and", enabled: true },
  { character: "岁", pinyin: "suì", english: "years of age", enabled: true },
  { character: "聚会", pinyin: "jùhuì", english: "party", enabled: true },
  { character: "祝贺", pinyin: "zhùhè", english: "congratulate", enabled: true },
  { character: "蛋糕", pinyin: "dàngāo", english: "cake", enabled: true },
  { character: "参加", pinyin: "cānjiā", english: "attend", enabled: true },
  { character: "快乐", pinyin: "kuàilè", english: "happy", enabled: true },
  { character: "漂亮", pinyin: "piàoliang", english: "beautiful", enabled: true },
  { character: "属", pinyin: "shǔ", english: "to be born in the year of", enabled: true },
  { character: "红酒", pinyin: "hóngjiǔ", english: "red wine", enabled: true },
  { character: "葡萄", pinyin: "pútáo", english: "grape", enabled: true },
  { character: "今年", pinyin: "jīnnián", english: "this year", enabled: true },
  { character: "上午", pinyin: "shàngwǔ", english: "morning", enabled: true },
  { character: "下午", pinyin: "xiàwǔ", english: "afternoon", enabled: true },
  { character: "买", pinyin: "mǎi", english: "buy", enabled: true },
  { character: "瓶", pinyin: "píng", english: "bottle (mw)", enabled: true },
  { character: "寿面", pinyin: "shòumiàn", english: "birthday noodles", enabled: true },
  { character: "过", pinyin: "guò", english: "to celebrate/spend time", enabled: true },
  { character: "光盘", pinyin: "guāngpán", english: "CD", enabled: true },
  { character: "音乐", pinyin: "yīnyuè", english: "music", enabled: true },
  { character: "常常", pinyin: "chángcháng", english: "often", enabled: true },
  { character: "跟", pinyin: "gēn", english: "with", enabled: true },
  { character: "钱", pinyin: "qián", english: "money", enabled: true },
  { character: "给", pinyin: "gěi", english: "give", enabled: true },
  { character: "报纸", pinyin: "bàozhǐ", english: "newspaper", enabled: true },
  { character: "书", pinyin: "shū", english: "book", enabled: true },
  { character: "商场", pinyin: "shāngchǎng", english: "mall", enabled: true },
  { character: "苹果", pinyin: "píngguǒ", english: "apple", enabled: true },
  { character: "容易", pinyin: "róngyì", english: "easy", enabled: true },
  { character: "送", pinyin: "sòng", english: "give as gift", enabled: true },
  { character: "毛", pinyin: "máo", english: "0.1 yuan", enabled: true },
  { character: "香蕉", pinyin: "xiāngjiāo", english: "banana", enabled: true },
  { character: "会", pinyin: "huì", english: "can/know how", enabled: true },
  { character: "司机", pinyin: "sījī", english: "driver", enabled: true },
  { character: "差", pinyin: "chà", english: "lack / short of", enabled: true },
  { character: "能", pinyin: "néng", english: "can (ability)", enabled: true },
  { character: "到", pinyin: "dào", english: "arrive", enabled: true },
  { character: "刻", pinyin: "kè", english: "15 minutes OR one quarter", enabled: true },
  { character: "回", pinyin: "huí", english: "return", enabled: true },
  { character: "教", pinyin: "jiāo", english: "teach", enabled: true },
  { character: "叫", pinyin: "jiào", english: "name(v) OR ask someone to do something", enabled: true },
  { character: "英语", pinyin: "yīngyǔ", english: "English", enabled: true },
  { character: "孙女儿", pinyin: "sūnnǚr", english: "granddaughter", enabled: true },
  { character: "岁数", pinyin: "suìshu", english: "age (polite)", enabled: true },
  { character: "玩儿", pinyin: "wánr", english: "play", enabled: true },
  { character: "半", pinyin: "bàn", english: "half", enabled: true },
  { character: "可是", pinyin: "kěshì", english: "but", enabled: true },
  { character: "写", pinyin: "xiě", english: "write", enabled: true },
  { character: "附近", pinyin: "fùjìn", english: "nearby (n)", enabled: true },
  { character: "睡觉", pinyin: "shuìjiào", english: "sleep", enabled: true },
  { character: "起床", pinyin: "qǐchuáng", english: "get up", enabled: true },
  { character: "应该", pinyin: "yīnggāi", english: "should", enabled: true },
  { character: "问题", pinyin: "wèntí", english: "question (n)", enabled: true },
  { character: "分钟", pinyin: "fēnzhōng", english: "minute (not when giving time)", enabled: true },
  { character: "块", pinyin: "kuài", english: "dollar", enabled: true },
  { character: "全身", pinyin: "quánshēn", english: "whole body", enabled: true },
  { character: "舒服", pinyin: "shūfu", english: "comfortable", enabled: true },
  { character: "锻炼", pinyin: "duànliàn", english: "exercise", enabled: true },
  { character: "看病", pinyin: "kànbìng", english: "see doctor", enabled: true },
  { character: "吧", pinyin: "ba", english: "modal particle", enabled: true },
  { character: "冷", pinyin: "lěng", english: "cold", enabled: true },
  { character: "想", pinyin: "xiǎng", english: "think/want", enabled: true },
  { character: "休息", pinyin: "xiūxi", english: "rest", enabled: true },
  { character: "挂号", pinyin: "guàhào", english: "register", enabled: true },
  { character: "发烧", pinyin: "fāshāo", english: "fever", enabled: true },
  { character: "感冒", pinyin: "gǎnmào", english: "cold", enabled: true },
  { character: "前天", pinyin: "qiántiān", english: "day before yesterday", enabled: true },
  { character: "后天", pinyin: "hòutiān", english: "day after tomorrow", enabled: true },
  { character: "药", pinyin: "yào", english: "medicine", enabled: true },
  { character: "住院", pinyin: "zhùyuàn", english: "hospitalized", enabled: true },
  { character: "离", pinyin: "lí", english: "A to B OR A from B", enabled: true },
  { character: "疼", pinyin: "téng", english: "painful", enabled: true },
  { character: "姑娘", pinyin: "gūniang", english: "girl", enabled: true },
  { character: "得", pinyin: "dé", english: "get", enabled: true },
  { character: "告诉", pinyin: "gàosu", english: "tell", enabled: true },
  { character: "电影", pinyin: "diànyǐng", english: "movie", enabled: true },
  { character: "再", pinyin: "zài", english: "again", enabled: true },
  { character: "还是", pinyin: "háishì", english: "or", enabled: true }
];
